name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Train model
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: python training.py --job_name ${{ github.sha }}
    
    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker australia-southeast1-docker.pkg.dev
        docker build -t australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-models/ml-model:${{ github.sha }} .
        docker push australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-models/ml-model:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ml-model \
            --image australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ml-models/ml-model:${{ github.sha }} \
          --platform managed \
          --region australia-southeast1 \
          --allow-unauthenticated